a<-read.csv('E2.csv')
names(a)=c("y","x1","x2","x3","x4","x5")
a$y=log(a$y)
library('dplyr')
group_by(a,x1) %>% summarise(N=n(),mean=mean(y),SD=sd(y),min=min(y),med=median(y),max=max(y))
group_by(a,x2) %>% summarise(N=n(),mean=mean(y),SD=sd(y),min=min(y),med=median(y),max=max(y))
group_by(a,x3) %>% summarise(N=n(),mean=mean(y),SD=sd(y),min=min(y),med=median(y),max=max(y))
group_by(a,x4) %>% summarise(N=n(),mean=mean(y),SD=sd(y),min=min(y),med=median(y),max=max(y))
group_by(a,x5) %>% summarise(N=n(),mean=mean(y),SD=sd(y),min=min(y),med=median(y),max=max(y))
lm<-lm(y~x1*x2+x3+x4+x5,data=a)
anova(lm)
summary(lm)
lm1<-lm(y~x1+x2+x4,data=a)
anova(lm1)
summary(lm1)